// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: check_solution.proto

package check_solution

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for GradingService service

func NewGradingServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for GradingService service

type GradingService interface {
	Grading(ctx context.Context, in *GradingRequest, opts ...client.CallOption) (*GradingResponse, error)
}

type gradingService struct {
	c    client.Client
	name string
}

func NewGradingService(name string, c client.Client) GradingService {
	return &gradingService{
		c:    c,
		name: name,
	}
}

func (c *gradingService) Grading(ctx context.Context, in *GradingRequest, opts ...client.CallOption) (*GradingResponse, error) {
	req := c.c.NewRequest(c.name, "GradingService.Grading", in)
	out := new(GradingResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GradingService service

type GradingServiceHandler interface {
	Grading(context.Context, *GradingRequest, *GradingResponse) error
}

func RegisterGradingServiceHandler(s server.Server, hdlr GradingServiceHandler, opts ...server.HandlerOption) error {
	type gradingService interface {
		Grading(ctx context.Context, in *GradingRequest, out *GradingResponse) error
	}
	type GradingService struct {
		gradingService
	}
	h := &gradingServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&GradingService{h}, opts...))
}

type gradingServiceHandler struct {
	GradingServiceHandler
}

func (h *gradingServiceHandler) Grading(ctx context.Context, in *GradingRequest, out *GradingResponse) error {
	return h.GradingServiceHandler.Grading(ctx, in, out)
}
